$axure
		.loadCurrentPage((function() {
			var _ = function() {
				var r = {}, a = arguments;
				for (var i = 0; i < a.length; i += 2)
					r[a[i]] = a[i + 1];
				return r;
			}
			var _creator = function() {
				return _(
						b,
						c,
						d,
						e,
						f,
						g,
						h,
						[ i, j, k, l, m, n, o ],
						p,
						_(
								q,
								r,
								s,
								t,
								u,
								o,
								v,
								_(),
								w,
								_(x, y, z, A, B, _(C, D, E, F), G, null, H, A,
										I, A, J, K, L, null, M, N, O, P, Q, R,
										S, N),
								T,
								_(),
								U,
								_(),
								V,
								_(
										W,
										[
												_(
														X,
														Y,
														Z,
														ba,
														s,
														bb,
														bc,
														bb,
														bd,
														be,
														w,
														_(B, _(C, D, E, bf),
																bg, _(bh, bi,
																		bj, bk)),
														T,
														_(),
														W,
														[ _(
																X,
																bl,
																Z,
																ba,
																bm,
																be,
																s,
																bn,
																bc,
																bo,
																bd,
																be,
																w,
																_(
																		B,
																		_(
																				C,
																				D,
																				E,
																				bf),
																		bg,
																		_(
																				bh,
																				bi,
																				bj,
																				bk)),
																T, _()) ], bp,
														_(bq, br)),
												_(
														X,
														bs,
														Z,
														ba,
														s,
														bb,
														bc,
														bo,
														bd,
														be,
														w,
														_(
																Q,
																bt,
																bu,
																bv,
																bw,
																bx,
																by,
																_(C, D, E, F,
																		bz, bA),
																bB,
																_(bC, bD, bE,
																		bF),
																bg,
																_(bh, bG, bj,
																		bH),
																bI, N, bJ, N),
														T,
														_(),
														W,
														[ _(
																X,
																bK,
																Z,
																ba,
																bm,
																be,
																s,
																bn,
																bc,
																bo,
																bd,
																be,
																w,
																_(
																		Q,
																		bt,
																		bu,
																		bv,
																		bw,
																		bx,
																		by,
																		_(
																				C,
																				D,
																				E,
																				F,
																				bz,
																				bA),
																		bB,
																		_(
																				bC,
																				bD,
																				bE,
																				bF),
																		bg,
																		_(
																				bh,
																				bG,
																				bj,
																				bH),
																		bI, N,
																		bJ, N),
																T, _()) ],
														U,
														_(
																bL,
																_(
																		bM,
																		bN,
																		bO,
																		[ _(
																				bM,
																				bP,
																				bQ,
																				g,
																				bR,
																				[ _(
																						bS,
																						bT,
																						bM,
																						bU,
																						bV,
																						_(
																								bW,
																								p,
																								b,
																								bX,
																								bY,
																								be),
																						bZ,
																						ca) ]) ])),
														cb, be, bp, _(bq, cc)),
												_(
														X,
														cd,
														Z,
														ba,
														s,
														bb,
														bc,
														bo,
														bd,
														be,
														w,
														_(
																Q,
																bt,
																bu,
																bv,
																bw,
																bx,
																by,
																_(C, D, E, F,
																		bz, bA),
																bB,
																_(bC, ce, bE,
																		bF),
																bg,
																_(bh, cf, bj,
																		bH),
																bI, N, bJ, N),
														T,
														_(),
														W,
														[ _(
																X,
																cg,
																Z,
																ba,
																bm,
																be,
																s,
																bn,
																bc,
																bo,
																bd,
																be,
																w,
																_(
																		Q,
																		bt,
																		bu,
																		bv,
																		bw,
																		bx,
																		by,
																		_(
																				C,
																				D,
																				E,
																				F,
																				bz,
																				bA),
																		bB,
																		_(
																				bC,
																				ce,
																				bE,
																				bF),
																		bg,
																		_(
																				bh,
																				cf,
																				bj,
																				bH),
																		bI, N,
																		bJ, N),
																T, _()) ], bp,
														_(bq, cc)),
												_(
														X,
														ch,
														Z,
														ba,
														s,
														bb,
														bc,
														bb,
														bd,
														be,
														w,
														_(
																Q,
																ci,
																bu,
																cj,
																bw,
																ck,
																by,
																_(C, D, E, F,
																		bz, bA),
																B, _(C, D, E,
																		bf),
																bB,
																_(bC, cl, bE,
																		cm),
																bg, _(bh, cn,
																		bj, cf)),
														T,
														_(),
														W,
														[ _(
																X,
																co,
																Z,
																ba,
																bm,
																be,
																s,
																bn,
																bc,
																bo,
																bd,
																be,
																w,
																_(
																		Q,
																		ci,
																		bu,
																		cj,
																		bw,
																		ck,
																		by,
																		_(
																				C,
																				D,
																				E,
																				F,
																				bz,
																				bA),
																		B,
																		_(
																				C,
																				D,
																				E,
																				bf),
																		bB,
																		_(
																				bC,
																				cl,
																				bE,
																				cm),
																		bg,
																		_(
																				bh,
																				cn,
																				bj,
																				cf)),
																T, _()) ],
														U,
														_(
																bL,
																_(
																		bM,
																		bN,
																		bO,
																		[
																				_(
																						bM,
																						cp,
																						bQ,
																						g,
																						cq,
																						_(
																								cr,
																								cs,
																								ct,
																								cu,
																								cv,
																								_(
																										cr,
																										cs,
																										ct,
																										cw,
																										cv,
																										_(
																												cr,
																												cx,
																												cy,
																												cz,
																												cA,
																												[ _(
																														cr,
																														cB,
																														cC,
																														g,
																														cD,
																														g,
																														cE,
																														g,
																														cF,
																														[ cG ]) ]),
																										cH,
																										_(
																												cr,
																												cI,
																												cF,
																												cJ,
																												cK,
																												[])),
																								cH,
																								_(
																										cr,
																										cs,
																										ct,
																										cw,
																										cv,
																										_(
																												cr,
																												cx,
																												cy,
																												cz,
																												cA,
																												[ _(
																														cr,
																														cB,
																														cC,
																														g,
																														cD,
																														g,
																														cE,
																														g,
																														cF,
																														[ cL ]) ]),
																										cH,
																										_(
																												cr,
																												cI,
																												cF,
																												cM,
																												cK,
																												[]))),
																						bR,
																						[
																								_(
																										bS,
																										bT,
																										bM,
																										bU,
																										bV,
																										_(
																												bW,
																												p,
																												b,
																												bX,
																												bY,
																												be),
																										bZ,
																										ca),
																								_(
																										bS,
																										cN,
																										bM,
																										cO,
																										cP,
																										_(
																												cr,
																												cQ,
																												cR,
																												[ _(
																														cr,
																														cx,
																														cy,
																														cS,
																														cA,
																														[
																																_(
																																		cr,
																																		cT,
																																		cU,
																																		o),
																																_(
																																		cr,
																																		cI,
																																		cF,
																																		cV,
																																		cK,
																																		[]) ]) ])) ]),
																				_(
																						bM,
																						cW,
																						bQ,
																						g,
																						bR,
																						[
																								_(
																										bS,
																										cX,
																										bM,
																										cY,
																										cZ,
																										[ _(
																												da,
																												[ db ],
																												dc,
																												_(
																														dd,
																														de,
																														df,
																														_(
																																dg,
																																dh))) ]),
																								_(
																										bS,
																										cN,
																										bM,
																										di,
																										cP,
																										_(
																												cr,
																												cQ,
																												cR,
																												[ _(
																														cr,
																														cx,
																														cy,
																														dj,
																														cA,
																														[
																																_(
																																		cr,
																																		cB,
																																		cC,
																																		g,
																																		cD,
																																		g,
																																		cE,
																																		g,
																																		cF,
																																		[ cG ]),
																																_(
																																		cr,
																																		cI,
																																		cF,
																																		ba,
																																		cK,
																																		[]) ]) ])),
																								_(
																										bS,
																										cN,
																										bM,
																										dk,
																										cP,
																										_(
																												cr,
																												cQ,
																												cR,
																												[ _(
																														cr,
																														cx,
																														cy,
																														dj,
																														cA,
																														[
																																_(
																																		cr,
																																		cB,
																																		cC,
																																		g,
																																		cD,
																																		g,
																																		cE,
																																		g,
																																		cF,
																																		[ cL ]),
																																_(
																																		cr,
																																		cI,
																																		cF,
																																		ba,
																																		cK,
																																		[]) ]) ])) ]) ])),
														cb, be, bp, _(bq, dl)),
												_(
														X,
														dm,
														Z,
														ba,
														s,
														bb,
														bc,
														bo,
														bd,
														be,
														w,
														_(Q, bt, bw, bx, dn,
																be, bB, _(bC,
																		cl, bE,
																		dp),
																bg,
																_(bh, dq, bj,
																		dr),
																bI, N, bJ, N),
														T,
														_(),
														W,
														[ _(
																X,
																ds,
																Z,
																ba,
																bm,
																be,
																s,
																bn,
																bc,
																bo,
																bd,
																be,
																w,
																_(
																		Q,
																		bt,
																		bw,
																		bx,
																		dn,
																		be,
																		bB,
																		_(
																				bC,
																				cl,
																				bE,
																				dp),
																		bg,
																		_(
																				bh,
																				dq,
																				bj,
																				dr),
																		bI, N,
																		bJ, N),
																T, _()) ],
														U,
														_(
																bL,
																_(
																		bM,
																		bN,
																		bO,
																		[ _(
																				bM,
																				bP,
																				bQ,
																				g,
																				bR,
																				[ _(
																						bS,
																						bT,
																						bM,
																						dt,
																						bV,
																						_(
																								bW,
																								p,
																								b,
																								du,
																								bY,
																								be),
																						bZ,
																						ca) ]) ])),
														cb, be, bp, _(bq, cc)),
												_(
														X,
														dv,
														Z,
														ba,
														s,
														bb,
														bc,
														bo,
														bd,
														be,
														w,
														_(Q, bt, bw, bx, dn,
																be, bB, _(bC,
																		dw, bE,
																		dp),
																bg,
																_(bh, dx, bj,
																		dr),
																bI, N, bJ, N),
														T,
														_(),
														W,
														[ _(
																X,
																dy,
																Z,
																ba,
																bm,
																be,
																s,
																bn,
																bc,
																bo,
																bd,
																be,
																w,
																_(
																		Q,
																		bt,
																		bw,
																		bx,
																		dn,
																		be,
																		bB,
																		_(
																				bC,
																				dw,
																				bE,
																				dp),
																		bg,
																		_(
																				bh,
																				dx,
																				bj,
																				dr),
																		bI, N,
																		bJ, N),
																T, _()) ],
														U,
														_(
																bL,
																_(
																		bM,
																		bN,
																		bO,
																		[ _(
																				bM,
																				bP,
																				bQ,
																				g,
																				bR,
																				[ _(
																						bS,
																						bT,
																						bM,
																						dt,
																						bV,
																						_(
																								bW,
																								p,
																								b,
																								du,
																								bY,
																								be),
																						bZ,
																						ca) ]) ])),
														cb, be, bp, _(bq, cc)),
												_(
														X,
														dz,
														Z,
														ba,
														s,
														dA,
														bc,
														dA,
														bd,
														be,
														w,
														_(bB,
																_(bC, dB, bE,
																		cf),
																bg,
																_(bh, dC, bj,
																		ce), S,
																dD, dE, _(C, D,
																		E, dF)),
														T,
														_(),
														W,
														[ _(
																X,
																dG,
																Z,
																ba,
																bm,
																be,
																s,
																bn,
																bc,
																bo,
																bd,
																be,
																w,
																_(
																		bB,
																		_(
																				bC,
																				dB,
																				bE,
																				cf),
																		bg,
																		_(
																				bh,
																				dC,
																				bj,
																				ce),
																		S,
																		dD,
																		dE,
																		_(
																				C,
																				D,
																				E,
																				dF)),
																T, _()) ], bp,
														_(bq, dH)),
												_(
														X,
														db,
														Z,
														dI,
														s,
														dJ,
														bc,
														dJ,
														bd,
														g,
														w,
														_(bB,
																_(bC, dK, bE,
																		dL),
																bg,
																_(bh, bD, bj,
																		bD),
																bd, g),
														T,
														_(),
														dM,
														dh,
														dN,
														be,
														dO,
														g,
														dP,
														[ _(
																X,
																dQ,
																Z,
																dR,
																s,
																dS,
																W,
																[ _(
																		X,
																		dT,
																		Z,
																		ba,
																		dU,
																		db,
																		dV,
																		dW,
																		s,
																		bb,
																		bc,
																		bo,
																		bd,
																		be,
																		w,
																		_(
																				Q,
																				bt,
																				bw,
																				bx,
																				by,
																				_(
																						C,
																						D,
																						E,
																						dX,
																						bz,
																						bA),
																				bg,
																				_(
																						bh,
																						dY,
																						bj,
																						dr)),
																		T,
																		_(),
																		W,
																		[ _(
																				X,
																				dZ,
																				Z,
																				ba,
																				bm,
																				be,
																				dU,
																				db,
																				dV,
																				dW,
																				s,
																				bn,
																				bc,
																				bo,
																				bd,
																				be,
																				w,
																				_(
																						Q,
																						bt,
																						bw,
																						bx,
																						by,
																						_(
																								C,
																								D,
																								E,
																								dX,
																								bz,
																								bA),
																						bg,
																						_(
																								bh,
																								dY,
																								bj,
																								dr)),
																				T,
																				_()) ],
																		bp,
																		_(bq,
																				cc)) ],
																w, _(B, _(C, D,
																		E, ea),
																		G,
																		null,
																		H, A,
																		I, A,
																		J, K),
																T, _()) ]),
												_(
														X,
														cG,
														Z,
														eb,
														s,
														ec,
														bc,
														ec,
														bd,
														be,
														w,
														_(bB,
																_(bC, cl, bE,
																		ed),
																bg, _(bh, cn,
																		bj, cl)),
														T,
														_(),
														U,
														_(
																ee,
																_(
																		bM,
																		ef,
																		bO,
																		[ _(
																				bM,
																				eg,
																				bQ,
																				g,
																				bR,
																				[ _(
																						bS,
																						cX,
																						bM,
																						eh,
																						cZ,
																						[ _(
																								da,
																								[ db ],
																								dc,
																								_(
																										dd,
																										ei,
																										df,
																										_(
																												dg,
																												dh))) ]) ]) ])),
														cb, be, ej, ek),
												_(
														X,
														cL,
														Z,
														el,
														s,
														ec,
														bc,
														ec,
														bd,
														be,
														w,
														_(bB,
																_(bC, cl, bE,
																		cn),
																bg, _(bh, cn,
																		bj, cl)),
														T, _(), ej, em) ])),
						en, _(), eo, _(ep, _(eq, er), es, _(eq, et), eu, _(eq,
								ev), ew, _(eq, ex), ey, _(eq, ez), eA,
								_(eq, eB), eC, _(eq, eD), eE, _(eq, eF), eG, _(
										eq, eH), eI, _(eq, eJ), eK, _(eq, eL),
								eM, _(eq, eN), eO, _(eq, eP), eQ, _(eq, eR),
								eS, _(eq, eT), eU, _(eq, eV), eW, _(eq, eX),
								eY, _(eq, eZ), fa, _(eq, fb)));
			};
			$.ajax({
				type : "get",
				url : "../rest/users/15867404048/123456",
				dataType : "json",
				data : {},
				success : function(data) {
					console.log(data);
				},
				error : function(XMLHttpRequest, textStatus, errorThrown) {
					alert(errorThrown);
				}
			});
			var b = "url", c = "login.html", d = "generationDate", e = new Date(
					1442908035235.28), f = "isCanvasEnabled", g = false, h = "variables", i = "OnLoadVariable", j = "index", k = "pay", l = "doctorIndex", m = "doctorIndexMov", n = "report", o = "login", p = "page", q = "packageId", r = "948995d26a514b47acd2f82d9c83778f", s = "type", t = "Axure:Page", u = "name", v = "notes", w = "style", x = "baseStyle", y = "627587b6038d43cca051c114ac41ad32", z = "pageAlignment", A = "near", B = "fill", C = "fillType", D = "solid", E = "color", F = 0xFFFFFFFF, G = "image", H = "imageHorizontalAlignment", I = "imageVerticalAlignment", J = "imageRepeat", K = "auto", L = "favicon", M = "sketchFactor", N = "0", O = "colorStyle", P = "appliedColor", Q = "fontName", R = "Applied Font", S = "borderWidth", T = "adaptiveStyles", U = "interactionMap", V = "diagram", W = "objects", X = "id", Y = "98f9ad724ea447e3b45ab09dafd9419f", Z = "label", ba = "", bb = "buttonShape", bc = "styleType", bd = "visible", be = true, bf = 0xFF00CC66, bg = "size", bh = "width", bi = 321, bj = "height", bk = 39, bl = "c1cec8d1cfad4ae89f0c4ec115dbefe7", bm = "isContained", bn = "richTextPanel", bo = "paragraph", bp = "images", bq = "normal~", br = "images/ask/u0.png", bs = "d84c3fbab6fe4f97844fc5f6021aeeb6", bt = "'Arial Black', 'Arial'", bu = "fontSize", bv = "18px", bw = "fontWeight", bx = "900", by = "foreGroundFill", bz = "opacity", bA = 1, bB = "location", bC = "x", bD = 10, bE = "y", bF = 8, bG = 50, bH = 22, bI = "rotation", bJ = "textRotation", bK = "6a9d3165aec8404ead3716de3a699e10", bL = "onClick", bM = "description", bN = "OnClick", bO = "cases", bP = "用例 1", bQ = "isNewIfGroup", bR = "actions", bS = "action", bT = "linkWindow", bU = "Open index in Current Window", bV = "target", bW = "targetType", bX = "index.html", bY = "includeVariables", bZ = "linkType", ca = "current", cb = "tabbable", cc = "resources/images/transparent.gif", cd = "1a98458d2e534fbb93c7734143611814", ce = 140, cf = 40, cg = "15d13234166942bb9ffe7419d6a26ab7", ch = "994c78d79f094a07936c4b535b5c45fc", ci = "'Arial Negreta', 'Arial'", cj = "16px", ck = "bold", cl = 30, cm = 350, cn = 260, co = "fccb03ae739d43acb606e8f90c5ef498",
					cp = "用例 1<br> (If text on phone_number equals &quot;15867404048&quot; and text on password equals &quot;123456&quot;)", cq = "condition", cr = "exprType", cs = "binaryOp", ct = "op", cu = "&&", cv = "leftExpr", cw = "==", cx = "fcall", cy = "functionName", cz = "GetWidgetText", cA = "arguments", cB = "pathLiteral", cC = "isThis", cD = "isFocused", cE = "isTarget", cF = "value", cG = "2d13803e894246ee949bb865da7309cb", cH = "rightExpr", cI = "stringLiteral", cJ = "15867404048", cK = "stos", cL = "f2a10fcb87d6402f9eea38cc2a55fedc", cM = "123456", cN = "setFunction", cO = "Set value of login equal to &quot;true&quot;", cP = "expr", cQ = "block", cR = "subExprs", cS = "SetGlobalVariableValue", cT = "globalVariableLiteral", cU = "variableName", cV = "true", cW = "Case 1<br> (Else If True)", cX = "fadeWidget", cY = "Show error", cZ = "objectsToFades", da = "objectPath", db = "6e6a421ff5c24c07a6138fd7a971c161", dc = "fadeInfo", dd = "fadeType", de = "show", df = "options", dg = "showType", dh = "none", di = "Set text on phone_number equal to &quot;&quot;", dj = "SetWidgetFormText", dk = "Set text on password equal to &quot;&quot;", dl = "images/login/u6.png", dm = "cd64df9061694b4bbafb8c7706ab2e21", dn = "underline", dp = 315, dq = 80, dr = 16, ds = "518e3f77e1b547868e25c071af4abc55", dt = "Open findPassword in Current Window", du = "findpassword.html", dv = "b65bba9d2aee43b7b7b207f4fbe0d020", dw = 210, dx = 60, dy = "955405b295f24beaaec22b336af51417", dz = "27f62dd6fd2f49898261ca12d032e999", dA = "imageBox", dB = 0, dC = 320, dD = "-1", dE = "borderFill", dF = 0xFF000000, dG = "d74a7cf8efe74e908575ba712c630759", dH = "images/service/u22.jpg", dI = "error", dJ = "dynamicPanel", dK = 55.5, dL = 400, dM = "scrollbars", dN = "fitToContent", dO = "propagate", dP = "diagrams", dQ = "fa469d16f9694d8b9ef21414a28082f2", dR = "State1", dS = "Axure:PanelDiagram", dT = "765ca3ac39dc47c69ba61a583502e868", dU = "parentDynamicPanel", dV = "panelIndex", dW = 0, dX = 0xFFFF0000, dY = 209, dZ = "1561f9eb42db4af9ab2bec8e560f30e0", ea = 0xFFFFFF, eb = "phone_number", ec = "textBox", ed = 200, ee = "onFocus", ef = "OnFocus", eg = "Case 1", eh = "Hide error", ei = "hide", ej = "placeholderText", ek = "用户名/手机号", el = "password", em = "密码", en = "masters", eo = "objectPaths", ep = "98f9ad724ea447e3b45ab09dafd9419f", eq = "scriptId", er = "u0", es = "c1cec8d1cfad4ae89f0c4ec115dbefe7", et = "u1", eu = "d84c3fbab6fe4f97844fc5f6021aeeb6", ev = "u2", ew = "6a9d3165aec8404ead3716de3a699e10", ex = "u3", ey = "1a98458d2e534fbb93c7734143611814", ez = "u4", eA = "15d13234166942bb9ffe7419d6a26ab7", eB = "u5", eC = "994c78d79f094a07936c4b535b5c45fc", eD = "u6", eE = "fccb03ae739d43acb606e8f90c5ef498", eF = "u7", eG = "cd64df9061694b4bbafb8c7706ab2e21", eH = "u8", eI = "518e3f77e1b547868e25c071af4abc55", eJ = "u9", eK = "b65bba9d2aee43b7b7b207f4fbe0d020", eL = "u10", eM = "955405b295f24beaaec22b336af51417", eN = "u11", eO = "27f62dd6fd2f49898261ca12d032e999", eP = "u12", eQ = "d74a7cf8efe74e908575ba712c630759", eR = "u13", eS = "6e6a421ff5c24c07a6138fd7a971c161", eT = "u14", eU = "765ca3ac39dc47c69ba61a583502e868", eV = "u15", eW = "1561f9eb42db4af9ab2bec8e560f30e0", eX = "u16", eY = "2d13803e894246ee949bb865da7309cb", eZ = "u17", fa = "f2a10fcb87d6402f9eea38cc2a55fedc", fb = "u18";
			return _creator();
		})());